#!/usr/bin/env python3
"""VISION の手書き見出し（src/content/vision-handwriting.ts）をフォントの輪郭から生成する。

使い方:
  pip install fonttools   （プロジェクトの依存には含めない。生成結果の .ts だけをコミットする）
  python3 scripts/handwriting-paths.py path/to/ZenKurenaido.ttf

フォント: Zen Kurenaido（SIL Open Font License 1.1、Google Fonts）。1 文字 = 1 ストロークとして
輪郭パスを書き出し、Handwriting.tsx が読み順に stroke-dashoffset で描き、続けて塗りをフェードインする。
文言を変えるときは LINES を書き換えて再実行する。
"""
import sys
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.pens.boundsPen import BoundsPen

LINES = ["仮面を外して、", "素の自分で。"]
LABEL = "".join(LINES)
SIZE = 84          # 1em の viewBox 単位
LINE_HEIGHT = 100  # 行送り
WIDTH = 640        # viewBox 幅（表示側は max-w-[560px] で縮小）
STROKE_WIDTH = 2.2 # 輪郭線の太さ（viewBox 単位）
OUT = "src/content/vision-handwriting.ts"

def main(font_path: str) -> None:
    font = TTFont(font_path)
    cmap = font.getBestCmap()
    glyphs = font.getGlyphSet()
    scale = SIZE / font["head"].unitsPerEm
    strokes: list[str] = []
    ymax = 0.0
    for li, line in enumerate(LINES):
        x = 0.0
        baseline = SIZE + li * LINE_HEIGHT
        for ch in line:
            name = cmap[ord(ch)]
            glyph = glyphs[name]
            pen = SVGPathPen(glyphs, ntos=lambda v: f"{v:.1f}".rstrip("0").rstrip("."))
            glyph.draw(TransformPen(pen, (scale, 0, 0, -scale, x, baseline)))
            bp = BoundsPen(glyphs)
            glyph.draw(TransformPen(bp, (scale, 0, 0, -scale, x, baseline)))
            if bp.bounds:
                ymax = max(ymax, bp.bounds[3])
            strokes.append(pen.getCommands())
            x += glyph.width * scale
        if x > WIDTH:
            raise SystemExit(f"line {li} overflows viewBox width: {x:.0f} > {WIDTH}")
    height = int(ymax + 8)
    body = ",\n".join(f'    {{ d: "{d}" }}' for d in strokes)
    ts = (
        "// GENERATED by scripts/handwriting-paths.py — 手で編集しない。文言を変えるときはスクリプトを再実行する。\n"
        "// フォント: Zen Kurenaido（SIL OFL 1.1）の輪郭を 1 文字 = 1 ストロークとして書き出したもの（2 行）。\n"
        "export const HANDWRITING = {\n"
        f'  viewBox: "0 0 {WIDTH} {height}",\n'
        f'  label: "{LABEL}",\n'
        f"  strokeWidth: {STROKE_WIDTH},\n"
        "  strokes: [\n"
        f"{body},\n"
        "  ] as { d: string; width?: number }[],\n"
        "};\n"
    )
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(ts)
    print(f"wrote {OUT}: {len(strokes)} glyphs, viewBox 0 0 {WIDTH} {height}, {len(ts)} bytes")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit("usage: handwriting-paths.py FONT.ttf")
    main(sys.argv[1])
