#!/usr/bin/env python3
"""VISION の手書き見出し（src/content/vision-handwriting.ts）を手書き画像（黒地に白の文字）のトレースから生成する。

使い方:
  pip install potracer numpy pillow   （プロジェクトの依存には含めない。生成結果の .ts だけをコミットする）
  python3 scripts/handwriting-trace.py "docs/ChatGPT Image 2026年9月18日 09_42_00 (2).png"

参考画像（2026-09-18 クライアント支給。docs/ は git 管理外）を 2 値化 → potrace で輪郭化 → 行は縦のインク量が最小の行で
2 行に分け、文字は BOUNDS の x 境界（元画像のピクセル）で 1 文字 = 1 ストロークに割り当てる。かすれの飛沫は
最寄りの文字に含める（TURD_SIZE 未満の点は捨てる）。Handwriting.tsx が読み順に stroke-dashoffset で輪郭を描き、続けて塗りをフェードインする。
画像を差し替えるときは CROP_TOP / BOUNDS を画像に合わせて直し、出力の各文字の輪郭数が 0 でないことを確認する。
フォントから生成する旧スクリプトは scripts/handwriting-paths.py。
"""
import sys
import numpy as np
from PIL import Image
import potrace

LINES = ["仮面を外して、", "素の自分で。"]
LABEL = "".join(LINES)
CROP_TOP = 340       # これより上（画像内の「VISION 私たちの想い」ラベル）は無視する
THRESHOLD = 128      # 明度がこれより大きい画素をインクとみなす
BOUNDS = [           # 文字境界（元画像の x）。輪郭の中心 x がどの区間に入るかで文字を決める
    [295, 485, 600, 808, 885, 1005],  # 仮|面|を|外|し|て|、
    [318, 460, 603, 845, 1009],       # 素|の|自|分|で|。
]
TURD_SIZE = 8        # これより小さい飛沫（画素数）は捨てる
OPT_TOLERANCE = 0.8  # 曲線の単純化（大きいほど軽いが形が崩れる）
WIDTH = 640          # viewBox 幅（表示側は max-w-[560px] で縮小）
MARGIN = 8
STROKE_WIDTH = 2.2   # 輪郭線の太さ（viewBox 単位）
OUT = "src/content/vision-handwriting.ts"


def main(image_path: str) -> None:
    gray = np.array(Image.open(image_path).convert("L"))
    gray[:CROP_TOP, :] = 0
    ink = gray > THRESHOLD
    ys = np.where(ink.any(axis=1))[0]
    y_lo, y_hi = int(ys.min()), int(ys.max())
    # 2 行の境: インク範囲の中央 40% で行方向のインク量が最小の行
    band = slice(y_lo + int((y_hi - y_lo) * 0.3), y_lo + int((y_hi - y_lo) * 0.7))
    split_y = band.start + int(np.argmin(ink[band].sum(axis=1)))
    # potracer は False を前景として扱うので反転して渡す
    curves = list(potrace.Bitmap(~ink).trace(turdsize=TURD_SIZE, alphamax=1.0, opttolerance=OPT_TOLERANCE))

    def points(c):
        pts = [(c.start_point.x, c.start_point.y)]
        pts += [(s.end_point.x, s.end_point.y) for s in c.segments]
        return pts

    boxes = []
    for c in curves:
        pts = points(c)
        xs = [p[0] for p in pts]
        ys_ = [p[1] for p in pts]
        boxes.append((min(xs), min(ys_), max(xs), max(ys_)))
    groups: dict[tuple[int, int], list[int]] = {}
    for i, (x0, y0, x1, y1) in enumerate(boxes):
        li = 0 if (y0 + y1) / 2 < split_y else 1
        cx = (x0 + x1) / 2
        ci = sum(1 for b in BOUNDS[li] if cx > b)
        groups.setdefault((li, ci), []).append(i)
    for li, line in enumerate(LINES):
        counts = [(ch, len(groups.get((li, ci), []))) for ci, ch in enumerate(line)]
        print(f"line {li}: {counts}")
        if any(n == 0 for _, n in counts):
            raise SystemExit("a character has no contour — adjust BOUNDS")

    x_min = min(b[0] for b in boxes)
    x_max = max(b[2] for b in boxes)
    y_min = min(b[1] for b in boxes)
    y_max = max(b[3] for b in boxes)
    scale = (WIDTH - MARGIN * 2) / (x_max - x_min)
    height = int((y_max - y_min) * scale + MARGIN * 2)
    fmt = lambda v: f"{v:.1f}".rstrip("0").rstrip(".")
    X = lambda p: fmt((p.x - x_min) * scale + MARGIN)
    Y = lambda p: fmt((p.y - y_min) * scale + MARGIN)

    def to_d(c) -> str:
        d = [f"M{X(c.start_point)} {Y(c.start_point)}"]
        for s in c.segments:
            if s.is_corner:
                d.append(f"L{X(s.c)} {Y(s.c)}L{X(s.end_point)} {Y(s.end_point)}")
            else:
                d.append(f"C{X(s.c1)} {Y(s.c1)} {X(s.c2)} {Y(s.c2)} {X(s.end_point)} {Y(s.end_point)}")
        d.append("Z")
        return "".join(d)

    strokes = [
        "".join(to_d(curves[i]) for i in groups[(li, ci)])
        for li, line in enumerate(LINES)
        for ci in range(len(line))
    ]
    body = ",\n".join(f'    {{ d: "{d}" }}' for d in strokes)
    ts = (
        "// GENERATED by scripts/handwriting-trace.py — 手で編集しない。画像や文言を変えるときはスクリプトを再実行する。\n"
        "// 元: クライアント支給の手書き画像（2026-09-18、docs/ 配下・git 管理外）を potrace で輪郭化し、1 文字 = 1 ストロークに分けたもの（2 行）。\n"
        "export const HANDWRITING = {\n"
        f'  viewBox: "0 0 {WIDTH} {height}",\n'
        f'  label: "{LABEL}",\n'
        f"  strokeWidth: {STROKE_WIDTH},\n"
        "  strokes: [\n"
        f"{body},\n"
        "  ] as { d: string; width?: number }[],\n"
        "};\n"
    )
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(ts)
    print(f"wrote {OUT}: {len(strokes)} glyphs from {len(curves)} contours, viewBox 0 0 {WIDTH} {height}, split_y {split_y}, {len(ts)} bytes")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit("usage: handwriting-trace.py IMAGE.png")
    main(sys.argv[1])
