// Google Fonts の css2 出力（@font-face + unicode-range スライス）を取得して public/fonts/ にセルフホストする。
// next/font/google はビルド時に毎回ダウンロードするため、回線が遅い環境（WSL2 等）でタイムアウトして
// フォールバックに落ちる。ミラーは 1 回だけ実行して生成物（woff2 + src/styles/fonts.css）をコミットする。
// 使い方: node scripts/mirror-fonts.mjs
import { mkdir, writeFile } from "node:fs/promises";

const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36";
const FONTS = [
  { slug: "inter-tight", css: "https://fonts.googleapis.com/css2?family=Inter+Tight:wght@100..900&display=swap", subsets: ["latin", "latin-ext"] },
  { slug: "noto-sans-jp", css: "https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100..900&display=optional", subsets: null }, // null = 全スライス
];

async function get(url, type) {
  for (let i = 1; i <= 4; i++) {
    try {
      const res = await fetch(url, { headers: { "user-agent": UA }, signal: AbortSignal.timeout(30000) });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      return type === "text" ? await res.text() : Buffer.from(await res.arrayBuffer());
    } catch (e) {
      if (i === 4) throw e;
      console.warn(`retry ${i}: ${url} (${e.message ?? e})`);
    }
  }
}

let out = "/* GENERATED by scripts/mirror-fonts.mjs — 手で編集しない */\n";
for (const f of FONTS) {
  const css = await get(f.css, "text");
  await mkdir(`public/fonts/${f.slug}`, { recursive: true });
  // スライスのコメント（/* latin */）が無い応答もあるため、無い場合は URL 末尾の連番（….12.woff2）を名前にする
  const blocks = [...css.matchAll(/(?:\/\* ([^*]+) \*\/\s*)?(@font-face \{[^}]+\})/g)];
  let kept = 0;
  for (const [, subsetRaw, block] of blocks) {
    const urlM = /url\((https:[^)]+\.woff2)\)/.exec(block);
    if (!urlM) continue;
    const subset = (subsetRaw ? subsetRaw.trim().replace(/[[\]]/g, "") : null) ?? /\.(\d+)\.woff2$/.exec(urlM[1])?.[1] ?? `x${kept}`;
    if (f.subsets && !f.subsets.includes(subset)) continue;
    const file = `${subset}.woff2`;
    await writeFile(`public/fonts/${f.slug}/${file}`, await get(urlM[1], "bin"));
    out += `/* ${f.slug} ${subset} */\n` + block.replace(urlM[1], `/fonts/${f.slug}/${file}`) + "\n";
    kept++;
  }
  console.log(`${f.slug}: ${kept} subsets`);
}
await writeFile("src/styles/fonts.css", out);
console.log(`wrote src/styles/fonts.css (${out.length} bytes)`);
